[package]
name = "c2pa-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c2pa = { version = "0.22.0", features = ["file_io"] }
tempfile = "3.5.0"
